In [1]:
import numpy as np
from math import cos, sin, pi

# Building and Transforming Coordinates
In this exercise you will expand upon our lecture content by building your own vector manipulations in 2D and 3D Cartesian space.
First, **implement a 2D rotation transformation**, `rotation_2d`, with input `theta`. 
It should return the $2\times 2$ matrix $R(\theta)$.

In [2]:
def rotation_2d(theta):
    return np.array([[cos(theta), -sin(theta)],[sin(theta), cos(theta)]])

Consider a coordinate frame, $A$, that is rotated $\frac{\pi}{2} \ rad$ relative to the origin frame $O$. Let ${}^Ap = [1.0 \ 0.0]^T$.
Predict what this vector would be with respect to the **original coordinate frame**, $O$ (Draw a picture!).
Apply your implement transformation function to verify!

In [3]:
# Prediction: we should have a vector [0.0 -1.0]^T
pA = np.array([1.,0.]).reshape(2,1)
# Apply your function...I rounded to make the numbers not so tiny.
R_OA = rotation_2d(pi/2.)
print(R_OA)
print(np.round(R_OA.dot(pA)))

[[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]
[[0.]
 [1.]]


Now, let's put this together with translation to make a `rigid_transformation2d` function that will take a vector, ${}^Xp$, defined in some frame $X$ and map it to a target frame $Y$.

**Inputs**: angle of rotation, $\theta$, and relative translation vector, ${}^Y\xi_X$.

**Outputs**: The $3 \times 3$ homogeneous matrix.

Useful `numpy` APIs: [`block`](https://numpy.org/doc/stable/reference/generated/numpy.block.html), [`append`](https://numpy.org/doc/stable/reference/generated/numpy.append.html).

In [4]:
def rigid_transformation2d(theta, xi):
    return np.block([[rotation_2d(theta), xi],[np.zeros((1,2)), 1.0]])

Based on the diagram in the class notes, let coordinate frame $A$ be translated by ${}^O\xi_A=[1.0, 1.0]^T$ and rotated by $\theta=\pi/2$ **relative to** $O$.
What is the vector ${}^Ap=[1.0, 2.0]^T$ in the $O$ coordinate frame? (e.g. ${}^Op$)

In [5]:
xi_OA = np.array([1.0, 1.0]).reshape(2,1)
T_OA = rigid_transformation2d(pi/2.0, xi_OA)
print(T_OA)

[[ 6.123234e-17 -1.000000e+00  1.000000e+00]
 [ 1.000000e+00  6.123234e-17  1.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]


In [6]:
pA_hom = np.array([1.,2.,1.]).reshape(3,1)
print(T_OA.dot(pA_hom))

[[-1.]
 [ 2.]
 [ 1.]]


With **same** details for frame $O$ and $A$, what would ${}^Op=[1.0, 0.0]^T$ be **with respect to frame** $A$?

In [7]:
# We use the fact that T_OA^-1 = T_AO!
pO_hom = np.array([1.0, 0.0, 1.0]).reshape(3,1)
T_AO = np.linalg.inv(T_OA)
print(np.round(T_AO.dot(pO_hom)))

[[-1.]
 [-0.]
 [ 1.]]


In [10]:
ap = np.array([2.0, 1.0, 1.0]).reshape(3,1)

xi_oa = np.array([4., 1.]).reshape(2,1)
xi_ob = np.array([1.,3.]).reshape(2,1)

t_oa = rigid_transformation2d(0, xi_oa)
op = t_oa.dot(ap)

t_ob = rigid_transformation2d(pi/6, xi_ob)
t_bo = np.linalg.inv(t_ob)

bp = t_bo.dot(op)
print(bp)

[[ 3.83012702]
 [-3.3660254 ]
 [ 1.        ]]
